export interface Product {
  id: string;
  title: string;
  price: number;
  description: string;
  shortDescription: string;
  image: string;
  images?: string[];
  tags: string[];
  category: string;
  inStock: boolean;
  stockCount?: number;
  featured?: boolean;
  bestseller?: boolean;
  compatibility?: string[];
  materials?: string;
  size?: string;
  rating?: number;
  reviewCount?: number;
  sku?: string;
  stock?: number;
  weight?: number;
  dimensions?: { length: number; width: number; height: number };
  shippingClass?: string;
}

export const products: Product[] = [
  {
    id: "daily-todos",
    title: "Icon Stickers | Daily To Do's",
    price: 5.50,
    shortDescription: "Essential lifestyle icon stickers for daily task tracking.",
    description: "Track your daily activities with these versatile icon stickers! Features lightbulbs, markers, weights, credit cards, sneakers, hearts, money, books, vitamins, salad bowls, coffee cups, apples, and more. Perfect for habit tracking, meal planning, exercise logging, and daily to-dos in soft peach, green, and brown tones.",
    image: "/images/product-daily-todos.jpg",
    tags: ["icons", "functional", "lifestyle", "habits"],
    category: "Icon Stickers",
    inStock: true,
    stockCount: 48,
    featured: true,
    bestseller: true,
    compatibility: ["All Planners", "Bullet Journals", "Hobonichi"],
    materials: "High-quality matte sticker paper",
    size: "One sheet with multiple icon stickers",
    rating: 4.9,
    reviewCount: 142
  },
  {
    id: "farm-kit",
    title: "Planner Kit | Cozy Farm Vibes",
    price: 6.50,
    shortDescription: "Complete farm-themed planner kit with functional elements.",
    description: "Embrace farm life! This comprehensive planner kit includes day headers, farm animals (chickens, birds), vegetables (carrots, corn, apples), jars, weekly trackers, to-do sections, motivational text like 'well done!', 'cool!', 'veggies time!', and 'need caffeine!'. Features habit tracker boxes and decorative farm elements in soft peachy-green tones.",
    image: "/images/product-farm-kit.png",
    tags: ["plannerkit", "farm", "kit", "functional", "nature"],
    category: "Planner Kits",
    inStock: true,
    stockCount: 32,
    featured: true,
    bestseller: true,
    compatibility: ["Weekly Planners", "Hobonichi Cousin", "Standard Planners"],
    materials: "Premium matte sticker paper with repositionable adhesive",
    size: "Full sheet with multiple functional elements",
    rating: 5.0,
    reviewCount: 98
  },
  {
    id: "farm-addon",
    title: "Planner Add-ons | Cozy Farm Vibes",
    price: 4.50,
    shortDescription: "Farm-themed decorative add-on stickers.",
    description: "Simple farm-themed add-ons perfect for any planner! Features repeating patterns of chickens with hearts, coffee cups, corn, jars, apples, and vegetable baskets. Great for decorating planner pages with a cozy farmhouse aesthetic.",
    image: "/images/product-farm-addon.png",
    tags: ["addons", "farm", "decorative", "nature"],
    category: "Add-ons",
    inStock: true,
    stockCount: 40,
    compatibility: ["All Planners", "Journals"],
    materials: "Matte sticker paper",
    size: "One sheet (P0004)",
    rating: 4.8,
    reviewCount: 67
  },
  {
    id: "forest-kit",
    title: "Planner Kit | Forest Magic",
    price: 6.50,
    shortDescription: "Complete forest-themed planner kit with woodland elements.",
    description: "Enter the enchanted forest! This comprehensive planner kit includes day headers, forest animals (foxes, mushrooms, acorns), trees, leaves, coffee cups, weekly trackers, to-do sections, motivational text like 'good job!', 'not bad!', 'nature time!', and 'yes!'. Features habit tracker boxes and decorative woodland elements in green, pink, and brown tones.",
    image: "/images/product-forest-kit.png",
    tags: ["plannerkit", "forest", "woodland", "kit", "functional", "nature"],
    category: "Planner Kits",
    inStock: true,
    stockCount: 35,
    featured: true,
    bestseller: true,
    compatibility: ["Weekly Planners", "Hobonichi Cousin", "Standard Planners"],
    materials: "Premium matte sticker paper with repositionable adhesive",
    size: "Full sheet with multiple functional elements",
    rating: 5.0,
    reviewCount: 134
  },
  {
    id: "forest-addon",
    title: "Planner Add-ons | Forest Magic",
    price: 4.50,
    shortDescription: "Forest-themed decorative add-on stickers.",
    description: "Bring the forest to your planner! Features repeating patterns of coffee cups, mushrooms, oak leaves, trees, apples, acorns, and foxes. Perfect for decorating planner pages with a magical woodland aesthetic in soft green, pink, and brown tones.",
    image: "/images/product-forest-addon.png",
    tags: ["addons", "forest", "woodland", "decorative", "nature"],
    category: "Add-ons",
    inStock: true,
    stockCount: 38,
    compatibility: ["All Planners", "Journals"],
    materials: "Matte sticker paper",
    size: "One sheet (P0005)",
    rating: 4.7,
    reviewCount: 82
  },
  {
    id: "frosty-adventures",
    title: "Seasonal Stickers | Frosty Adventures",
    price: 5.50,
    shortDescription: "Winter-themed stickers with polar bears, penguins, and snow.",
    description: "Winter wonderland awaits! These seasonal stickers feature adorable polar bears in sweaters, penguins with hot chocolate, reindeer, and frosted trees. Perfect for winter planning and celebrating the snowy season in soft pastels.",
    image: "/images/product-frosty-adventures.jpg",
    tags: ["seasonal", "winter", "christmas", "animals"],
    category: "Seasonal",
    inStock: true,
    stockCount: 42,
    featured: true,
    bestseller: true,
    compatibility: ["All Planners", "Journals"],
    materials: "High-quality matte sticker paper",
    size: "One sheet - Frosty Adventures",
    rating: 4.9,
    reviewCount: 156
  },
  {
    id: "halloween-weekly-kit-2",
    title: "Halloween Weekly Planner Kit",
    price: 6.50,
    shortDescription: "Complete Halloween weekly planner kit with functional trackers.",
    description: "Ultimate Halloween planning! This comprehensive kit includes weekly day letters (m/t/w/t/f/s/s), habit trackers with cute Halloween icons (black cats, pumpkins, skulls, ghosts), motivational stickers ('Good Job!', 'Daily 30' Workout!', 'Eat your Veggies!', 'Self-Care!'), full and half boxes, checklists, and decorative elements in soft pastels.",
    image: "/images/product-halloween-weekly-kit.png",
    tags: ["plannerkit", "halloween", "seasonal", "weekly", "kit", "functional"],
    category: "Planner Kits",
    inStock: true,
    stockCount: 30,
    featured: true,
    bestseller: true,
    compatibility: ["Weekly Planners", "Hobonichi Weeks", "Standard Planners"],
    materials: "Premium matte sticker paper with repositionable adhesive",
    size: "Full sheet - Halloween Weekly Planner Kit",
    rating: 5.0,
    reviewCount: 187
  },
  {
    id: "happy-holidays",
    title: "Seasonal Stickers | Happy Holidays",
    price: 5.50,
    shortDescription: "Christmas holiday stickers with ornaments, hot cocoa, and trees.",
    description: "Holiday cheer in every sticker! Features adorable polar bears, hot chocolate mugs with whipped cream and gifts, Christmas ornaments, and tiny Christmas trees. Perfect for holiday planning in festive pink, green, and cream tones.",
    image: "/images/product-happy-holidays.jpg",
    tags: ["seasonal", "christmas", "holiday", "winter"],
    category: "Seasonal",
    inStock: true,
    stockCount: 36,
    featured: true,
    bestseller: true,
    compatibility: ["All Planners", "Journals"],
    materials: "High-quality matte sticker paper",
    size: "One sheet - Happy Holidays!",
    rating: 4.9,
    reviewCount: 203
  },
  {
    id: "healthy-meal-time",
    title: "Planner Stickers | Healthy Meal Time!",
    price: 5.50,
    shortDescription: "Healthy eating stickers with vegetables and Mr. Boo.",
    description: "Eat your veggies! These stickers feature Mr. Boo with various healthy foods including onions, bok choy, peas in pod, carrots, and vegetable combinations. Perfect for meal planning, nutrition tracking, and healthy eating goals in soft green and peachy tones.",
    image: "/images/product-healthy-meal.jpg",
    tags: ["planner", "food", "healthy", "mrboo", "functional"],
    category: "Planner Stickers",
    inStock: true,
    stockCount: 44,
    featured: true,
    compatibility: ["All Planners", "Meal Planners", "Health Journals"],
    materials: "High-quality matte sticker paper",
    size: "One sheet - Healthy Meal Time! (912, 910, 192)",
    rating: 4.8,
    reviewCount: 115
  },
  {
    id: "mrboo-halloween-notes",
    title: "Holiday Add-ons | Mr. Boo Halloween Notes",
    price: 4.50,
    shortDescription: "Halloween-themed note stickers with Mr. Boo and spooky frames.",
    description: "Spooky notes! Features Mr. Boo ghost shapes perfect for writing notes, plus Halloween-themed frames with mummies, bats, and stitches. Perfect for adding fun note sections to your Halloween planning.",
    image: "/images/product-mrboo-halloween-notes.png",
    tags: ["addons", "halloween", "notes", "mrboo", "seasonal"],
    category: "Add-ons",
    inStock: true,
    stockCount: 34,
    compatibility: ["All Planners", "Journals", "Notebooks"],
    materials: "Matte sticker paper",
    size: "One sheet (H0002)",
    rating: 4.7,
    reviewCount: 91
  },
  {
    id: "boo-moods",
    title: "Planner Stickers | Mr. Boo Daily Moods",
    price: 5.50,
    shortDescription: "Adorable mood tracker stickers featuring Mr. Boo characters.",
    description: "Track your daily moods with Mr. Boo! These charming stickers feature a variety of emotional expressions from drinking coffee to feeling peaceful. Perfect for daily mood tracking in planners and journals. Features multiple emotions and activities in cute character form.",
    image: "/images/product-boo-moods.png",
    tags: ["planner", "mrboo", "moodtracker", "functional", "cute"],
    category: "Planner Stickers",
    inStock: true,
    stockCount: 50,
    featured: true,
    bestseller: true,
    compatibility: ["All Planners", "Hobonichi", "Bullet Journals"],
    materials: "High-quality matte sticker paper",
    size: "One sheet (B0001)",
    rating: 5.0,
    reviewCount: 142
  },
  {
    id: "mood-boosters",
    title: "Planner Add-ons | Daily Mood Boosters",
    price: 5.50,
    shortDescription: "Coffee-themed mood booster stickers for daily planning.",
    description: "Start your day right with these adorable coffee cup stickers! Perfect for tracking your daily caffeine intake or mood boosters. Features various coffee drinks including lattes, espressos, and mugs in soft pastel colors.",
    image: "/images/product-mood-boosters.png",
    tags: ["addons", "coffee", "moodtracker", "functional"],
    category: "Add-ons",
    inStock: true,
    stockCount: 45,
    featured: true,
    compatibility: ["All Planners", "Journals"],
    materials: "Premium matte sticker paper",
    size: "One sheet (E0002)",
    rating: 4.9,
    reviewCount: 88
  },
  {
    id: "cleaning-chores",
    title: "Planner Stickers | Cleaning Chores",
    price: 5.50,
    shortDescription: "Fun stickers to track cleaning tasks and chores.",
    description: "Make chore tracking fun! Features Mr. Boo with cleaning supplies including sponges, spray bottles, and buckets. Perfect for household planning and cleaning schedules. Includes various poses showing different cleaning activities.",
    image: "/images/product-cleaning-chores.jpg",
    tags: ["planner", "functional", "chores", "cleaning", "mrboo"],
    category: "Planner Stickers",
    inStock: true,
    stockCount: 38,
    featured: true,
    compatibility: ["All Planners", "Household Planners"],
    materials: "High-quality matte sticker paper",
    size: "One sheet - Time for Chores",
    rating: 4.8,
    reviewCount: 65
  },
  {
    id: "coffee-kit",
    title: "Planner Kit | Coffee is Love, Coffee is Life",
    price: 6.50,
    shortDescription: "Complete coffee-themed planner kit with functional elements.",
    description: "For coffee lovers! This comprehensive planner kit includes day headers, coffee icons, clouds, to-do boxes, checkboxes, and motivational text like 'need coffee', 'not bad!', 'yes!', and 'latte love'. Features a weekly tracker section and decorative coffee-themed elements in soft browns and blues.",
    image: "/images/product-coffee-kit.png",
    tags: ["plannerkit", "coffee", "kit", "functional"],
    category: "Planner Kits",
    inStock: true,
    stockCount: 35,
    featured: true,
    bestseller: true,
    compatibility: ["Weekly Planners", "Hobonichi Cousin", "Standard Planners"],
    materials: "Premium matte sticker paper with repositionable adhesive",
    size: "Full sheet with multiple functional elements",
    rating: 5.0,
    reviewCount: 156
  },
  {
    id: "coffee-addon",
    title: "Planner Add-ons | Coffee is Love, Coffee is Life",
    price: 4.50,
    shortDescription: "Coffee-themed decorative add-on stickers.",
    description: "Simple coffee-themed add-ons perfect for any planner! Features coffee beans, clouds, cups, envelopes, and coins in a minimalist brown and blue palette. Great for decorating planner pages or marking special coffee moments.",
    image: "/images/product-coffee-addon.png",
    tags: ["addons", "coffee", "decorative"],
    category: "Add-ons",
    inStock: true,
    stockCount: 42,
    compatibility: ["All Planners", "Journals"],
    materials: "Matte sticker paper",
    size: "One sheet (P0001)",
    rating: 4.7,
    reviewCount: 73
  },
  {
    id: "coffee-time",
    title: "Planner Stickers | Coffee Time (Powered by Coffee)",
    price: 5.50,
    shortDescription: "Coffee-powered stickers featuring Mr. Boo and coffee drinks.",
    description: "Powered by Coffee! These stickers combine Mr. Boo with various coffee drinks - from cold brew to hot cups. Perfect for coffee lovers who want to track their daily caffeine adventures. Features multiple coffee styles and Mr. Boo enjoying his favorite beverages.",
    image: "/images/product-coffee-time.jpg",
    tags: ["planner", "coffee", "mrboo", "functional"],
    category: "Planner Stickers",
    inStock: true,
    stockCount: 40,
    featured: true,
    compatibility: ["All Planners", "Coffee Journals"],
    materials: "High-quality matte sticker paper",
    size: "One sheet - Powered by Coffee",
    rating: 4.9,
    reviewCount: 124
  },
  {
    id: "cosy-cute",
    title: "Planner Stickers | Cosy & Cute",
    price: 5.50,
    shortDescription: "Cozy lifestyle stickers with Mr. Boo and everyday items.",
    description: "Embrace the cozy life! Features Mr. Boo with coffee, plants, blankets, books, burgers, mushrooms, and pears. Perfect for tracking self-care, meals, reading time, and cozy moments. Includes various lifestyle icons in soft, muted colors.",
    image: "/images/product-cosy-cute.png",
    tags: ["planner", "lifestyle", "cozy", "mrboo", "selfcare"],
    category: "Planner Stickers",
    inStock: true,
    stockCount: 36,
    featured: true,
    bestseller: true,
    compatibility: ["All Planners", "Bullet Journals", "Hobonichi"],
    materials: "High-quality matte sticker paper",
    size: "Large sheet - Cosy & Cute (N60, 312, 026)",
    rating: 5.0,
    reviewCount: 198
  },
  {
    id: "cozy-autumn",
    title: "Seasonal Stickers | Cozy Autumn Vibes",
    price: 5.50,
    shortDescription: "Fall-themed stickers with squirrels, pumpkins, and pumpkin spice lattes.",
    description: "Fall in love with autumn! These seasonal stickers feature adorable squirrels with acorns, pumpkins, Mr. Boo in fall attire, and pumpkin spice lattes. Perfect for autumn planning and celebrating cozy fall vibes.",
    image: "/images/product-cozy-autumn.jpg",
    tags: ["seasonal", "autumn", "fall", "pumpkin", "mrboo"],
    category: "Seasonal",
    inStock: true,
    stockCount: 44,
    featured: true,
    bestseller: true,
    compatibility: ["All Planners", "Journals"],
    materials: "High-quality matte sticker paper",
    size: "One sheet - Cozy Autumn Vibes",
    rating: 4.9,
    reviewCount: 167
  },
  {
    id: "cozy-corner",
    title: "Deco Stickers | Cozy Corner",
    price: 5.50,
    shortDescription: "Comfort-themed deco stickers with food, nature, and Mr. Boo.",
    description: "Create your cozy corner! Features Mr. Boo with coffee, umbrellas, mushrooms, eggs, burgers, leaves, croissants, and cups. Perfect for decorating planner pages with comfort and lifestyle themes in soft green and warm tones.",
    image: "/images/product-cozy-corner.jpg",
    tags: ["deco", "lifestyle", "cozy", "mrboo", "food"],
    category: "Deco Stickers",
    inStock: true,
    stockCount: 33,
    featured: true,
    compatibility: ["All Planners", "Journals", "Scrapbooks"],
    materials: "High-quality matte sticker paper",
    size: "One sheet - Cozy Corner (026, 946, 912)",
    rating: 4.8,
    reviewCount: 109
  },
  {
    id: "halloween-planner-kit",
    title: "Halloween Planner Kit",
    price: 5.50,
    shortDescription: "Complete Halloween weekly planner kit with functional and decorative stickers.",
    description: "Everything you need for a spooky-cute planner spread! This comprehensive Halloween planner kit includes functional headers, weekly tracker boxes, decorative elements, checkboxes, and adorable Mr. Boo stickers. Features habit trackers, motivational quotes, and pastel color-coded sections perfect for weekly planning. Includes full and half boxes, icons, and decorative strips.",
    image: "/images/product-halloween-kit.png",
    tags: ["plannerkit", "halloween", "seasonal", "kit", "functional"],
    category: "Planner Kits",
    inStock: true,
    stockCount: 42,
    featured: false,
    bestseller: false,
    compatibility: ["Weekly Planners", "Hobonichi Weeks", "Standard Planners"],
    materials: "Premium matte sticker paper with repositionable adhesive",
    size: "Full sheet with multiple functional and decorative elements",
    rating: 4.9,
    reviewCount: 78
  },
  {
    id: "mrboo-halloween",
    title: "Holiday Planner Stickers | Mr. Boo's Favorite Season",
    price: 3.30,
    shortDescription: "Adorable Halloween stickers featuring Mr. Boo and friends.",
    description: "Meet Mr. Boo! These charming Halloween stickers feature Mr. Boo the cat along with ghosts, pumpkins, witch hats, candy, and cozy autumn elements. Perfect for adding a cute spooky touch to your planner pages. Printed on high-quality matte sticker paper.",
    image: "/images/product-mrboo.png",
    tags: ["planner", "halloween", "seasonal", "mrboo", "cute"],
    category: "Seasonal",
    inStock: true,
    stockCount: 38,
    featured: true,
    bestseller: true,
    compatibility: ["All Planners", "Hobonichi", "Field Notes"],
    materials: "High-quality matte sticker paper",
    size: "One sheet, multiple stickers",
    rating: 5.0,
    reviewCount: 95
  },
  {
    id: "halloween-stickers",
    title: "Holiday Planner Stickers | Halloween",
    price: 3.30,
    shortDescription: "Cute Halloween planner stickers, perfect for Hobonichi & Field Notes.",
    description: "Cute Halloween planner stickers, printed on high-quality matte sticker paper. Features friendly ghosts, pumpkins, and autumn leaves in our signature pastel palette. Perfect for adding a festive touch to your Hobonichi planner or Field Notes journal.",
    image: "/images/product-halloween.jpg",
    tags: ["planner", "halloween", "seasonal", "hobonichi", "fieldnotes"],
    category: "Seasonal",
    inStock: true,
    stockCount: 45,
    featured: true,
    bestseller: true,
    compatibility: ["Hobonichi", "Field Notes", "Standard Planner"],
    materials: "High-quality matte sticker paper",
    size: "One sheet, multiple stickers",
    rating: 4.9,
    reviewCount: 127
  },
  {
    id: "peachy-planner-kit",
    title: "Planner Kit | Everything is Peachy (Hobonichi Cousin Compatible)",
    price: 5.50,
    shortDescription: "Complete planner kit sized for Hobonichi Cousin.",
    description: "Complete planner kit with headers, boxes, and deco stickers in our peachy theme. Sized perfectly for Hobonichi Cousin planners. Includes functional headers, decorative boxes, and cute accent stickers to brighten every page.",
    image: "/images/product-peachy.jpg",
    tags: ["plannerkit", "hobonichi", "kit", "peach"],
    category: "Planner Kits",
    inStock: true,
    stockCount: 23,
    featured: true,
    bestseller: true,
    compatibility: ["Hobonichi Cousin"],
    materials: "Premium matte sticker paper with repositionable adhesive",
    size: "Hobonichi Cousin size",
    rating: 5.0,
    reviewCount: 89
  },
  {
    id: "fieldnotes-addons",
    title: "Field Notes Add-ons | Functional Basics",
    price: 2.80,
    shortDescription: "Small functional stickers perfect for Field Notes journals.",
    description: "Essential functional stickers designed specifically for Field Notes notebooks. Includes checkboxes, flags, stars, tabs, and priority markers in soft teal and coral. Perfect for bullet journaling and daily planning.",
    image: "/images/product-fieldnotes.jpg",
    tags: ["fieldnotes", "functional", "addons", "bulletjournal"],
    category: "Field Notes Add-ons",
    inStock: true,
    stockCount: 67,
    featured: true,
    compatibility: ["Field Notes", "Small Notebooks"],
    materials: "Matte sticker paper",
    size: "Field Notes compatible",
    rating: 4.8,
    reviewCount: 156
  },
  {
    id: "spring-seasonal",
    title: "Seasonal Collection | Spring Blooms",
    price: 3.50,
    shortDescription: "Spring-themed stickers with flowers and butterflies.",
    description: "Celebrate spring with these delicate floral stickers featuring flowers, butterflies, and nature elements in pastel peach and teal. Perfect for adding a fresh, seasonal touch to any planner or journal.",
    image: "/images/product-spring.jpg",
    tags: ["seasonal", "spring", "flowers", "planner"],
    category: "Seasonal",
    inStock: true,
    stockCount: 34,
    bestseller: false,
    compatibility: ["All Planners", "Journals"],
    materials: "High-quality matte sticker paper",
    size: "Standard sheet",
    rating: 4.7,
    reviewCount: 93
  },
  {
    id: "minimalist-headers",
    title: "Minimalist Headers | Neutral Tones",
    price: 2.50,
    shortDescription: "Simple, elegant header stickers for any planner.",
    description: "Clean and minimal header stickers in neutral warm tones. Perfect for sectioning your planner pages with style. Works with any planner system.",
    image: "/images/product-peachy.jpg",
    tags: ["headers", "minimalist", "functional", "planner"],
    category: "Planner Kits",
    inStock: true,
    stockCount: 52,
    compatibility: ["All Planners"],
    materials: "Matte sticker paper",
    size: "Various sizes on one sheet",
    rating: 4.6,
    reviewCount: 71
  },
  {
    id: "hobonichi-weeks",
    title: "Hobonichi Weeks Stickers | Daily Icons",
    price: 3.00,
    shortDescription: "Tiny functional icons for Hobonichi Weeks planners.",
    description: "Specially sized for Hobonichi Weeks! Tiny, functional icons for tracking habits, appointments, and daily tasks. Includes weather, activities, meals, and mood trackers.",
    image: "/images/product-fieldnotes.jpg",
    tags: ["hobonichi", "weeks", "functional", "tracking"],
    category: "Planner Kits",
    inStock: true,
    stockCount: 41,
    featured: false,
    compatibility: ["Hobonichi Weeks"],
    materials: "Matte sticker paper",
    size: "Hobonichi Weeks size",
    rating: 4.9,
    reviewCount: 134
  },
  {
    id: "christmas-holiday",
    title: "Holiday Planner Stickers | Christmas Joy",
    price: 3.30,
    shortDescription: "Festive Christmas stickers in soft pastels.",
    description: "Celebrate the holidays with these adorable Christmas-themed stickers. Features trees, ornaments, gifts, and winter elements in our signature soft color palette.",
    image: "/images/product-halloween.jpg",
    tags: ["christmas", "holiday", "seasonal", "planner"],
    category: "Seasonal",
    inStock: true,
    stockCount: 28,
    bestseller: true,
    compatibility: ["All Planners"],
    materials: "High-quality matte sticker paper",
    size: "Standard sheet",
    rating: 4.8,
    reviewCount: 112
  },
  {
    id: "washi-sampler",
    title: "Washi Tape Sample Set | Pastels",
    price: 4.20,
    shortDescription: "Sample set of our most popular washi tape patterns.",
    description: "Try all our favorite washi patterns! This sampler includes short rolls of 5 different pastel washi tapes. Perfect for decorating planner pages, envelopes, and craft projects.",
    image: "/images/product-spring.jpg",
    tags: ["washi", "tape", "sampler", "crafts"],
    category: "Add-ons",
    inStock: true,
    stockCount: 19,
    materials: "Japanese washi paper",
    size: "5 rolls, 50cm each",
    rating: 4.7,
    reviewCount: 64
  }
];

export const categories = [
  "All",
  "Planner Kits",
  "Planner Stickers",
  "Icon Stickers",
  "Deco Stickers",
  "Seasonal",
  "Field Notes Add-ons",
  "Add-ons"
];

export const tags = [
  "planner",
  "hobonichi",
  "fieldnotes",
  "seasonal",
  "functional",
  "kit",
  "washi",
  "mrboo",
  "coffee",
  "moodtracker",
  "cozy",
  "lifestyle",
  "cute",
  "icons",
  "farm",
  "nature",
  "forest",
  "woodland",
  "winter",
  "halloween",
  "christmas",
  "holiday",
  "healthy",
  "food"
];
